// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS-jtLBIehOuUrEZhkms1zishCluW54LU',
    appId: '1:253046876722:web:0a37dc6e6fdf5bd0a6aa2b',
    messagingSenderId: '253046876722',
    projectId: 'tame-the-beast',
    authDomain: 'tame-the-beast.firebaseapp.com',
    storageBucket: 'tame-the-beast.appspot.com',
    measurementId: 'G-THMCJXXQB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD-pL_9JpfsX0Q4bp3TIRSNr9EiisjIYw',
    appId: '1:253046876722:android:1e86c18c69531f3fa6aa2b',
    messagingSenderId: '253046876722',
    projectId: 'tame-the-beast',
    storageBucket: 'tame-the-beast.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTxq8QroNRRCC71ypvPxchpsI9Z74oc-w',
    appId: '1:253046876722:ios:fc16ff71dad08212a6aa2b',
    messagingSenderId: '253046876722',
    projectId: 'tame-the-beast',
    storageBucket: 'tame-the-beast.appspot.com',
    iosClientId: '253046876722-0f2jikb139dv4ci7s0v7l1v7ppdre954.apps.googleusercontent.com',
    iosBundleId: 'com.example.tameTheBeast',
  );
}
